model:
  type: MLP_nonorm
  ndim: 10
  nwell: 2
  num_steps: 1000
  scaling: 6
  beta_min: 1.e-5
  beta_max: 1.e-2
  hidden_size: 50
  hidden_layers: 1
  emb_size: 10

train:
  batch_size: 128
  num_epoch: 81
  decay_steps: 20
  lr: 2.e-4
  noise_offset: 0.0
  opt: torch.optim.AdamW
  if_v: True
  
dataset:
  name: GMM

Sampler:
  ode_steps: 20
  tmax: 1.0
  rho: 2

SMC:
  n_steps: 2000
  nmc: 2
  n_replicas: 1000
  Kmax_x: 10
  Kmax_eps: 10
  Kmin_x: 1
  Kmin_eps: 1
  compress_exp_x: 0.05
  compress_exp_eps: 0.05
  ess_threshold: 0.95
  resample_method: systematic


